dist: xenial
language: go
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_extended_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
  - go get -u -v github.com/bep/s3deploy
  - s3deploy -V
script:
  - hugo
  - s3deploy -source=public/ -region=us-east-1 -bucket=jonathanfoster.io
