language: go
install:
  - go get github.com/gohugoio/hugo
script:
  - hugo version
  - hugo
deploy:
  provider: s3
  access_key_id:
    secure: euGoMiHJdtRfCXL5GJktuT7AK25Dvc5UDMa+jE73Tmxirf3mSOjxx6m7SaRXyHiYODYVbk//XLS5lQ/gq5zUfIQe2aJt+60zI0Dk2oT2ro/IGclgVriDr10GfHw3dm/AqUCVQoqaJ08l4NUMuWO8b4YlMO4TEU2i3+gbOeKRG87Qo3e0E3r+6SLJHRKzBnODTLGvyOXdhrgT1Xb15F0RhKZoD1pOn+lLA0P35gjugiCHhyN1LmpSGepEBi0Fbydy92GxFMQIrCzKX5xnMxkCVHYsfMQMHwhByOfre/WfS6LcvkXuZj2AqdRfNtifCf/kDIeRELFMLRoxYuD/QQovGZTvXgqU5uMb1epLJ+mt5/y9ZaMHxs+Ekfmp8/rEYzgD/K50ZK/ouka5V8OdzO3rW8BhvPbVL7wEBTDBe/Ep6T9k997Kjprq5bRegQLktusvVEGq8+rfD4RPpNVMXBdhXyDOuO7eol+XJsuj7H0n1DDdD70suQRzjayoPl1kbOuK+uCeelS2K1jC7zB+urGPYja9V1ajUtzmFK8GX5SVpd0ITg6wuAaSgnMMCOMbAuF5P09sk0yYncjULacKoW/0LUwHlFkczX83b5+MGYaqQqj4xJez1zl4DPkNMaHs0MkemWOAp926girdSzOjYDhuhSC/CBaUSX+L90Y8qvklUmI=
  secret_access_key:
    secure: RUfvy0wOooCNp/EoEPc71/RTFsqCqZ8pHK8dpxsSdgjduj833wR4/YhdV3929S/WzqaBfot5ROsOEIiq669dfOUXB+TJkD9aTgF3TOrHDtvGjHNwtC9O6ROY7seLFbJtQrxt0Yae4ql3A+S66KW7fmZLHnXhy8IEYj/77ut/mCI18Ks5JcdZ7+BYy46O4ezI1iChyRxoxHt1logZkx6XU3zeBl/BWV4RU/2//3uzptRN+Qi620Z+kTcaw2UqYYZeJanD5i/O+d63RuNc3GHJa+p1RDIKtQD8jH6GcOj3ef8us8NinIX7A4zN07IOOEzMz5FpII7+J2u7hdqFbI1Xn4Bn6isgkkjYY+Vu27A7+ttnOGOoanKw0rxwcWkgKe8V0qT/s6W3//6/Bk+LCXxUZeeNrdy2F8yuwWC35gcMFyuleWy3GNKcxWSyoGTpUcYjOglBEctlde+j6RaonxGMw+YV/12ea1an8TbbwjEddWXczaGOF5SoW6dbN4Q55G6HNCpbzZMwVZsNE5RWgwiVPL1ndd3i3kP5XpeyXO7XkNk3sLaE7DcVBmx0Pmc3QMfKlhGPLgldnEpLV8mhTL7fLkzhqVEhhQ4wMVki4iUVh6GnjIgc1KqJMTaRce/akzSHgJIR1Yv0p+zsGwlE3TgbX9ebAS9gtPFGYuyPPhxBDUI=
  bucket: jonathanfoster.io
  local_dir: public
  skip_cleanup: true
  acl: public_read
