dist: xenial
language: python
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_extended_0.52_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
  - pip install awscli
  - aws --version
script:
  - hugo
  - ./scripts/deploy.sh
