baseURL = "https://jonathanfoster.io"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Jonathan Foster"
theme = "hermit"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = false
rssLimit = 10
copyright = "Foster Technologies LLC"
enableEmoji = true
googleAnalytics = "UA-54367932-1"

[author]
  name = "Jonathan Foster"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#111111"
  homeSubtitle = "Maker of things."
  footerCopyright = 'Foster Technologies LLC'
  gitUrl = "https://github.com/jonathanfoster/jonathanfoster.io/commit/"
  justifyContent = false

  [[params.social]]
    name = "github"
    url = "https://github.com/jonathanfoster"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/jonathanefoster"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jonathanefoster"
